platform :ios, '11.0'

target 'RelatedDigitalExample' do
  use_frameworks!
  pod 'RelatedDigitalIOS', :path => '../'
  pod 'CleanyModal'
end

target 'RelatedDigitalExampleTests' do
  use_frameworks!
  pod 'RelatedDigitalIOS', :path => '../'
  pod 'CleanyModal'
end


