 platform :ios, '12.0'

target 'RelatedDigitalExample' do
  use_frameworks!
  pod 'RelatedDigitalIOS', :path => '../'
  pod 'CleanyModal'
  pod "SplitRow", :git => 'https://github.com/EurekaCommunity/SplitRow.git'
end

target 'NotificationService' do
  use_frameworks!
  pod 'RelatedDigitalIOS', :path => '../'
  
end

target 'NotificationContent' do
  use_frameworks!
  pod 'RelatedDigitalIOS', :path => '../'  
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      if target.name == 'RelatedDigitalIOS'
        config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'No'
      end
    end
  end
end
