name: CI
on:
  push:
    branches: [ master]
  pull_request:
    branches: [ master]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['OS=14.4,name="iPhone 11"']

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      working-directory: Example
      run:
        pod install --repo-update
    - name: Run Test
      working-directory: Example
      run: |
        xcodebuild -workspace RelatedDigitalExample.xcworkspace -scheme RelatedDigitalExample -derivedDataPath Build/ -destination ${{ matrix.destination }} -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES -enableCodeCoverage YES clean build test | xcpretty -c;
        set -o pipefail
    - name: Pod Lint
      run: pod lib lint --allow-warnings